# Generated by Django 3.1.2 on 2020-10-28 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('user_id', models.BigIntegerField(default=1, unique=True, verbose_name='ID Users Telegram')),
                ('name', models.CharField(max_length=100, verbose_name='Full name of user')),
                ('username', models.CharField(max_length=100, null=True, verbose_name='Username Telegram')),
                ('tel', models.CharField(max_length=100, null=True, verbose_name='tel')),
            ],
            options={
                'verbose_name': 'Пользователь',
                'verbose_name_plural': 'Пользователи',
            },
        ),
    ]
