# Generated by Django 3.1.2 on 2020-10-29 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usermanage', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('customer_id', models.BigIntegerField(default=1, unique=True, verbose_name='id of customer')),
                ('date', models.CharField(max_length=50, verbose_name='Date of order')),
                ('time', models.CharField(max_length=50, verbose_name='Time of order')),
                ('type', models.CharField(max_length=50, verbose_name='Type of order')),
                ('amount', models.BigIntegerField(verbose_name='Amount')),
                ('typeofevent', models.CharField(max_length=100, verbose_name='Typeofevent ')),
            ],
            options={
                'verbose_name': 'Заказ',
                'verbose_name_plural': 'Заказы',
            },
        ),
    ]
