# Generated by Django 3.1.2 on 2020-10-30 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usermanage', '0002_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='customer_id',
            field=models.BigIntegerField(default=1, verbose_name='id of customer'),
        ),
    ]
